spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: '{cipher}AQAL20lqg+fNOT3aRefgIs/6C0I6aOH+k1K6K+TLH8F5gjCFzXMRt6PGOrN4pR9KAfBvF6pVl/Cb22w5RBsrjYAp7+4QIHswlf4p2rpEQY7Pa9PABUaGr/n44+geTT4M6FNfT/DrNPhkTFAK4fcoD8PeIYj5Wa8Y03wC4x9xE/4X3wPZXhF+HvIXnvrvHg3OouPjKORXP3KQmKSVDmifwX2DHIxeZ/ePW1z3+7qX57sBEe/D/pk8QFC4d/PttvH4wAQZU3EBVMZk22nCyYc/eAqNrZYjS2aXDIeRX4p1bgfBE0VxVOpv3ib/Y0BB+ZqtxhfLsu1Mre5cAdwqbTIKP3LtuS/z+sKDThJ6gyd9y1aWZGuuDtX+0cWQNiPsLn9+WNY='
    password: 
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  rabbitmq:
    host: rabbit
    port: 5672

security:
  oauth2:
    resource:
      user-info-uri: http://identidades:8095/user
      filter-order: 3

management:
  contextPath: /manage
  security.enabled: false
  
http:
  client:
    ssl:
      trust-store: shared/truststores/truststore.jks
      trust-store-password: changeit

eureka:
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client: 
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    
flyway:
  validate-on-migrate: false
  table: SCHEMA_VERSION
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}  
  custom-migration.enabled: true # Ativa a migração usando spring beans no core
  
hystrix.command.default.execution.isolation:
  strategy: SEMAPHORE
  thread.timeoutInMilliseconds: 10000

encrypt:
  keyStore:
    location: shared/truststores/truststore.jks
    password: changeit
    alias: stfdigital
    secret: changeit