spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/xe
    username: usuarioautuacao
    password: oracle
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  activiti:
      database-schema: activitiautuacao
 
flyway:
  url: jdbc:oracle:thin:@oracle:1521/xe
  user: flywayautuacao
  password: oracle
  locations:
    - classpath:db/migration
    - classpath:db/structure/flyway/callbacks
