spring:
  datasource:
    url: qaurlconnection
    username: '{cipher}AQAIhEqTfpXkR/GIk1QZM9XZBQbsTTzVs2JxmuyI8aVctJuudUAM3EU/bneemG0+4ySLj4AzFluavJH5ecEtfuB1FVfadFg1LnLkFVYeaTdBkp2F2mJo7MrxBpHj+PEErZPWD+qC2rHrggAz1r3d4EXLbv3JYMBNFVApnz+drfq78ewACp+rrEJNSjt5hSXNSXYcn4EjmejE2kUrskCYm2eZj0W2yuL1LuFk0UI33KKygEDLPxj6e3jfEh0mJGqfzfCMMWHVUIh2tsElM10XsXlPSYa/FOgU9NhET64fbW8sIs8bkZ0r5blQGbYd11EKbFOfMXBGdbDZ7ecMj8CRk4JdIHSFMOiNwnWDCKoUUiu/RRMx+RQiE5ACHZD6DQ6nlS8='
    password: '{cipher}AQAPdcuVGmbz4PhhI+SAl8B+KNrtLXCSA2YDDEcr+ha5fkexJTxkZfPrNDDS7s70ROt13m+fw1zGp5Ee6HWHKNG+rgBuAohN0C6guukEfZlI31qnI5VwyHnzkLKpMt9+KqHhMFkU0W5yMbkDt7Ptgmq4lMyyQWI1jAg+wwyAVidt96ot6syM3GVbkpG0DQkv/WoYr1lsiofPW9cfLn6Wp7qzD1rXcPU8HPdkW6+rsiAFdaaS9F/I8F/P504ghf6olBdlZZC4MUhZqR+g2EfuAbpKpHd/I8Kbs+xrn/LloIkReWS7UXC2Z2vSNOj0zkBpxy9+itLeKbs1g/wME56EmYhxXtHN4kfBAhPVUfjm0bVDktUBP6N6D14R8wqUbxw2DmM='
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
