spring:
  datasource:
    url: jdbc:oracle:thin:@bd-orcl-stfdigitalq:1521/stfdigitalq
    username: usuarioautuacao
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  activiti:
    database-schema: activitiautuacao
    
flyway:
  url: jdbc:oracle:thin:@bd-orcl-stfdigitalq:1521/stfdigitalq
  user: flywayautuacao
  password: 123
  locations:
  - classpath:db/migration
  - classpath:db/structure/flyway/callbacks