server:
  port: 8093
  
spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema:
      - classpath:db-development/schema.sql
      - classpath:db-development/import.sql 
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      
