spring:
  datasource:
    url: jdbc:oracle:thin:@bd-orcl-stfdigital:1521/pdb_autuacao
    username: usuarioautuacao
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  activiti:
    database-schema: activitiautuacao
    
flyway:
  url: jdbc:oracle:thin:@bd-orcl-stfdigital:1521/pdb_autuacao
  user: flywayautuacao
  password: 123
  locations:
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks




integracao.url-ambiente: http://sistemas.stf.jus.br