server:
  port: 8093
  
spring:
  datasource:
    initialize: true
    url: jdbc:h2:mem:${spring.application.name};MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema:
      - classpath:db-development/schema.sql
    data:
      - classpath:db-development/data.sql 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      
