spring: 
  datasource:
    url: jdbc:oracle:thin:@bd-orcl-stfdigitalq:1521/stfdigitalq
    username: usuariodocuments
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  data:
    cassandra:
      contact-points: bd-csnd-stfdigitalq
      username: usuariodocuments
      password: AQAPGOGpS3HVlLLqmd5Yj5OLBshexfvHFgBULadLD+4zKxQBpS/ctLW0Ra44k/9ZdR761szaf5H/CXKWP1jd7KgBWsw1NMrAa7Mo06TzEZiuj277YKWjX7aFCkTg8UIEbdTJh77ol/A/brWDUxZIKIiiZTs3m+/Bgywzb0RT3QBN74CcH5kWWw/4507hqRCOLhnIBzeMNiDNk6y9Thl2DVduOD47G4JDgxJ0v4g4UKAEU7TJ21MlaE/9Wb65KYCHHsQLxpz3IOrOMts1HnI6WeI+wciJlyCt9TQf6WdvVpxvxduetJH/qqkn3nHUOAvXRJb0t3ONb2dL+DkOldWI1NzGXv6UbIqPY7ciDcxRBs+QClxgub69aHZDOCqelntoKyZyyY6a8ywzZA7lEyewjmVg
onlyoffice: 
  server:
    address: https://onlyofficet.stf.jus.br
  integration:
    address: https://onlyofficet.stf.jus.br
    port: 443
  documentserver:
    host: digitalq.stf.jus.br
    port: 30790

flyway: 
  url: jdbc:oracle:thin:@bd-orcl-stfdigitalq:1521/stfdigitalq
  user: flywaydocuments
  password: 123
  locations: 
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks