spring: 
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/xe
    username: usuariodocuments
    password: oracle
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
 
onlyoffice: 
  server:
    address: '{cipher}AQCPiAVUIW/raWtzCDFE80n30/qeSUN+8LS1szKmnz21wex3mMfs49haBHzMk7Qpz/JTsZ+5Fc1cZL5KDul7uEHTE8YOIHWrmMG9+zxWlXxREEZEcvps7a/pA6rw97UHYsdlv/7zmj+YH7fE9vgp1E2XsUAncifTmOgO6p+onx517/d5Vo+QDFjwyycpZf4M9H7NS0rcICQ/R0+f2hSHWtX/sKw9ze2IT8YMHlAvXk2Dkc+En5VDwgJx/FXhB1nK54M6vmiv8kVwSwU+OqzG06Pk7sfjqwnjIQDiTS13JgGiis+8QiB1fDeG5M8nxzYRF4aerKoR05AGcaO2VwNfexxVjBOgrdiIT0LEgkN0Xnn007FjsArJXok5Dsz3rn1uL7/+0j3wSZVVvK7xDmJjkjoH'
  integration:
    address: onlyofficet.stf.jus.br
    port: '{cipher}AQCCKcDT6LPENTQ21tpkmGGqZRcGmfYs+Iu/cUed+0c/6Yf8VSvHZt8ayKlmL4xGIKHkdiX/cwKhoKpeOfrwLiweMMQDX6cP3RqtecJSt0pyGqGYiF+KjKXP/UrqqFI3oNu4+bJhk5++DsGwz+7VyfPGsCxLvh+b1Nq4y59JittxyQRY5/Zg1KlyxfKOT3j8yugEGT4UvUmtOGEIdg5zZYzOj/9vbCOu7kBdoiGoI7abz+4BnoMKuK7FafaT1PrIWBvrRvA3TakXRIsbGEORsyPPb6msb+NOy4/Lhuc3W6YktRDWJ/0+SP7HT7QZByKgQrjaEFn+RVcWy4R45x1Q/Ifxbfu9ZzeXJHcqJl9/PtBYHey1ZjDblyDQBG2JAIpUmJQ='
  documentserver:
    host: stfdigital2
    port: '{cipher}AQAzwhKNM1JrNxPRmGluyoN8Vqcc7reMP2b8lFSUqvKtkSbRefvGCGbxhIGyWgwLtWbITlp6AJgOwjdzDR3qL8dQ52urIdH727SQ/54eDpfQRXdIe59wMLDAQVuK/vnoxSeuk2s9z5zjoY4/XOSMRDvpVCwWGW0/B5Qdy2lTk5gJmAt+snHqDwAMMp60iKiqaCQ2VWz1zhU2kMp7Lh/Lbj3D7lDtbUsN72rCgssfixWJk004PzJZkLpxQ/wG+LvjnKQkzxENfA5KQ/CoNVLdzNnqzBpPdXZU+sDPeYBUZu4fl11ab+mig+OiD9zc3N0mxqQSsaN7uk/E4sMKfIgxv9hq5eCGINkWB/Zpu3h2uayFJZzTYOuHUhmCsicaJtis5LM='

flyway: 
  url: jdbc:oracle:thin:@oracle:1521/xe
  user: flywaydocuments
  password: oracle
  locations: 
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks
