spring:
  datasource:
    url: jdbc:oracle:thin:@stfdigital:1521/poc
    username: usuarioidentificador
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

flyway:
  url: jdbc:oracle:thin:@stfdigital:1521/poc
  user: flywayidentificador
  password: 123