spring:
  datasource:
    url: jdbc:oracle:thin:@bd-orcl-stfdigitalh:1521/pdb_recebimento
    username: usuariorecebimento
    password: 123
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  activiti:
    database-schema: recebimento
    database-schema-update: true
    
flyway:
  url: jdbc:oracle:thin:@bd-orcl-stfdigitalh:1521/pdb_recebimento
  user: flywayrecebimento
  password: 123
  locations:
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks
  
