spring:
  datasource:
    url: jdbc:oracle:thin:@docker:1521/xe
    username: SYSTEM
    password: oracle
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    activiti:
      database-schema: activitiautuacao
 
flyway:
  url: jdbc:oracle:thin:@docker:1521/xe
  user: SYSTEM
  password: oracle
  schemas: flywayrecebimento
  initSqls: CREATE USER RECEBIMENTO IDENTIFIED BY recebimento ACCOUNT UNLOCK; ALTER USER SYSTEM quota unlimited on SYSTEM
  locations:
    - classpath:db/migration
    - classpath:db/structure/flyway/callbacks
