spring:
  datasource:
    url: jdbc:oracle:thin:@docker:1521/xe
    username: usuariorecebimento
    password: oracle
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    activiti:
      database-schema: activitiautuacao
 
flyway:
  url: jdbc:oracle:thin:@docker:1521/xe
  user: usuarioflyway
  password: oracle
  locations:
    - classpath:db/migration
    - classpath:db/structure/flyway/callbacks
